In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('survey_results_public.csv')

In [3]:
df.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompTotal',
       'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [4]:
df['ConvertedCompYearly']

0         62268.0
1             NaN
2             NaN
3             NaN
4             NaN
           ...   
83434    160500.0
83435      3960.0
83436     90000.0
83437    816816.0
83438     21168.0
Name: ConvertedCompYearly, Length: 83439, dtype: float64

In [5]:
df=df[['Employment','EdLevel','Country','YearsCodePro','ConvertedCompYearly']]

In [6]:
import numpy as np

In [7]:
type(df['YearsCodePro'])

pandas.core.series.Series

In [8]:
df.isnull().sum()

Employment               116
EdLevel                  313
Country                    0
YearsCodePro           22223
ConvertedCompYearly    36595
dtype: int64

In [9]:
df=df.rename({'ConvertedCompYearly':'Salary'},axis=1)

In [10]:
df.head(10)

Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Student, full-time   
2                                 Student, full-time   
3                                 Employed full-time   
4  Independent contractor, freelancer, or self-em...   
5                                 Student, part-time   
6                                I prefer not to say   
7                                 Student, full-time   
8                                 Employed part-time   
9                                 Employed full-time   

                                             EdLevel  \
0  Secondary school (e.g. American high school, G...   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
5       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
6  Secondary school (e.g. American high school, G...   
7       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
8       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   

                                             Country YearsCodePro   Salary  
0                                           Slovakia          NaN  62268.0  
1                                        Netherlands          NaN      NaN  
2                                 Russian Federation          NaN      NaN  
3                                            Austria          NaN      NaN  
4  United Kingdom of Great Britain and Northern I...           10      NaN  
5                           United States of America          NaN      NaN  
6                           United States of America          NaN      NaN  
7                                           Malaysia          NaN      NaN  
8                                              India            4      NaN  
9                                             Sweden            4  51552.0

In [11]:
df=df[df['Salary'].notnull()]

In [12]:
df.head(10)

Employment  \
0   Independent contractor, freelancer, or self-em...   
9                                  Employed full-time   
11                                 Employed full-time   
12                                 Employed full-time   
16                                 Employed full-time   
17                                 Employed full-time   
18                                I prefer not to say   
23                                 Employed full-time   
24                                 Employed full-time   
26                                 Employed full-time   

                                              EdLevel      Country  \
0   Secondary school (e.g. American high school, G...     Slovakia   
9     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)       Sweden   
11       Bachelor’s degree (B.A., B.S., B.Eng., etc.)        Spain   
12    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)      Germany   
16       Bachelor’s degree (B.A., B.S., B.Eng., etc.)       Turkey   
17       Bachelor’s degree (B.A., B.S., B.Eng., etc.)       Canada   
18         Other doctoral degree (Ph.D., Ed.D., etc.)    Singapore   
23    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)       France   
24    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)      Germany   
26    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  Switzerland   

   YearsCodePro    Salary  
0           NaN   62268.0  
9             4   51552.0  
11            5   46482.0  
12            6   77290.0  
16            2   17748.0  
17            6   46135.0  
18           30  160932.0  
23            2   38915.0  
24           18   77831.0  
26            5   81319.0

In [13]:
df=df.dropna()

In [14]:
df.isnull().sum()

Employment      0
EdLevel         0
Country         0
YearsCodePro    0
Salary          0
dtype: int64

In [15]:
df['Employment'].unique()

array(['Employed full-time', 'I prefer not to say',
       'Independent contractor, freelancer, or self-employed',
       'Employed part-time', 'Retired'], dtype=object)

In [16]:
df['YearsCodePro'].unique()

array(['4', '5', '6', '2', '30', '18', '21', '16', '10',
       'Less than 1 year', '15', '3', '1', '12', '8', '7', '17', '14',
       '26', '25', '34', '11', '24', '22', '13', '9', '20', '31', '23',
       '39', '27', '35', '19', '33', 'More than 50 years', '37', '43',
       '40', '29', '38', '32', '45', '42', '28', '46', '36', '44', '47',
       '41', '50', '49', '48'], dtype=object)

In [17]:
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'
df['EdLevel']=df['EdLevel'].apply(clean_education)

In [18]:
def clean_emp(x):
    if 'Employed full-time' in x:
        return 'Employed full-time'
    if 'Employed part-time' in x:
        return 'Employed part-time'
    if 'Independent contractor, freelancer, or self-employed' in x:
        return 'self-employed'
    if 'I prefer not to say' in x:
        return 'prefer not to say'
    if 'Retired' in x:
        return 'Retired' 
df['Employment']=df['Employment'].apply(clean_emp)

In [19]:
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [20]:
df.head(10)

Employment            EdLevel  \
9   Employed full-time    Master’s degree   
11  Employed full-time  Bachelor’s degree   
12  Employed full-time    Master’s degree   
16  Employed full-time  Bachelor’s degree   
17  Employed full-time  Bachelor’s degree   
18   prefer not to say          Post grad   
23  Employed full-time    Master’s degree   
24  Employed full-time    Master’s degree   
26  Employed full-time    Master’s degree   
27  Employed full-time  Bachelor’s degree   

                                              Country  YearsCodePro    Salary  
9                                              Sweden           4.0   51552.0  
11                                              Spain           5.0   46482.0  
12                                            Germany           6.0   77290.0  
16                                             Turkey           2.0   17748.0  
17                                             Canada           6.0   46135.0  
18                                          Singapore          30.0  160932.0  
23                                             France           2.0   38915.0  
24                                            Germany          18.0   77831.0  
26                                        Switzerland           5.0   81319.0  
27  United Kingdom of Great Britain and Northern I...          21.0   68507.0

In [21]:
df['Country'].value_counts()

United States of America                                9800
India                                                   3750
Germany                                                 3221
United Kingdom of Great Britain and Northern Ireland    2915
Canada                                                  1721
                                                        ... 
Dominica                                                   1
Saint Kitts and Nevis                                      1
Guinea                                                     1
Monaco                                                     1
North Korea                                                1
Name: Country, Length: 171, dtype: int64

In [22]:
def shorten_categories(categories,cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if(categories[i]>=cutoff):
            categorical_map[categories.index[i]] = categories.index[i]
            #print(categories.index[i])
        else:
            categorical_map[categories.index[i]] = 'Other'
    #print(categorical_map)
    return categorical_map

In [23]:
country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

United States of America                                9800
Other                                                   9530
India                                                   3750
Germany                                                 3221
United Kingdom of Great Britain and Northern Ireland    2915
Canada                                                  1721
France                                                  1619
Brazil                                                  1572
Poland                                                  1106
Netherlands                                             1052
Spain                                                   1027
Australia                                                948
Italy                                                    917
Russian Federation                                       871
Sweden                                                   820
Switzerland                                              561
Turkey                  

In [24]:
df.head(10)

Employment            EdLevel  \
9   Employed full-time    Master’s degree   
11  Employed full-time  Bachelor’s degree   
12  Employed full-time    Master’s degree   
16  Employed full-time  Bachelor’s degree   
17  Employed full-time  Bachelor’s degree   
18   prefer not to say          Post grad   
23  Employed full-time    Master’s degree   
24  Employed full-time    Master’s degree   
26  Employed full-time    Master’s degree   
27  Employed full-time  Bachelor’s degree   

                                              Country  YearsCodePro    Salary  
9                                              Sweden           4.0   51552.0  
11                                              Spain           5.0   46482.0  
12                                            Germany           6.0   77290.0  
16                                             Turkey           2.0   17748.0  
17                                             Canada           6.0   46135.0  
18                                              Other          30.0  160932.0  
23                                             France           2.0   38915.0  
24                                            Germany          18.0   77831.0  
26                                        Switzerland           5.0   81319.0  
27  United Kingdom of Great Britain and Northern I...          21.0   68507.0

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le_education=LabelEncoder()
df['EdLevel']=le_education.fit_transform(df['EdLevel'])
df['EdLevel'].unique()

array([2, 0, 3, 1])

In [27]:
le_country=LabelEncoder()
df['Country']=le_country.fit_transform(df['Country'])
df['Country'].unique()

array([21, 20,  9, 23,  5, 17,  8, 22, 25, 19, 12, 24, 26,  4, 13, 15, 18,
        2, 10,  7,  1,  3, 11,  0, 16,  6, 14])

In [28]:
le_emp=LabelEncoder()
df['Employment']=le_emp.fit_transform(df['Employment'])
df['Employment'].unique()

array([0, 3, 4, 1, 2])

In [29]:
df.head()

Employment  EdLevel  Country  YearsCodePro   Salary
9            0        2       21           4.0  51552.0
11           0        0       20           5.0  46482.0
12           0        2        9           6.0  77290.0
16           0        0       23           2.0  17748.0
17           0        0        5           6.0  46135.0

In [30]:
X=df.drop('Salary',axis=1)
Y=df['Salary']

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lreg=LinearRegression()

In [33]:
Y

9         51552.0
11        46482.0
12        77290.0
16        17748.0
17        46135.0
           ...   
83434    160500.0
83435      3960.0
83436     90000.0
83437    816816.0
83438     21168.0
Name: Salary, Length: 46359, dtype: float64

In [34]:
lreg.fit(X,Y.values)

LinearRegression()

In [35]:
y_pred = lreg.predict(X)

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np
error=np.sqrt(mean_absolute_error(Y,y_pred))

In [37]:
error

331.35438792837857

In [38]:
from sklearn.tree import DecisionTreeRegressor

In [39]:
dreg=DecisionTreeRegressor()

In [40]:
dreg.fit(X,Y.values)

DecisionTreeRegressor()

In [41]:
y_pred=dreg.predict(X)

In [42]:
error=np.sqrt(mean_absolute_error(Y,y_pred))

In [43]:
error

313.7030580758749

In [44]:
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, Y.values)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [45]:
regressor = gs.best_estimator_

regressor.fit(X, Y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(Y, y_pred))
print("${:,.02f}".format(error))

$522,423.45


# Saving the model

## Decision tree Regressor

In [46]:
import pickle as pkl

In [47]:
data={"model":dreg,"le_emp":le_emp,"le_education":le_education,"le_country":le_country}
with open('save_model.pkl','wb') as file:
    pkl.dump(data,file)

In [48]:
with open('save_model.pkl','rb') as file:
    data=pkl.load(file)

In [49]:
regressor_loaded = data["model"]
le_emp=data["le_emp"]
le_country = data["le_country"]
le_education = data["le_education"]

In [50]:
X = np.array([["Employed part-time","Bachelor’s degree","Germany",5]])

In [51]:
X[:,0]=le_emp.transform(X[:,0])

In [52]:
X[:,1]=le_education.transform(X[:,1])

In [53]:
X[:2]=le_country.transform(X[:,2])

In [54]:
X = X.astype(float)

In [55]:
y_p=regressor_loaded.predict(X)

C:\Anaconda\envs\ml\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [56]:
y_p

array([129718.])

In [57]:
y_p[0]

129718.0

In [58]:
c=df[df['Salary']>=y_p[0]]

In [62]:
sorted_df = c.sort_values(by='Salary')

In [64]:
sorted_df.tail(10)

Employment  EdLevel  Country  YearsCodePro      Salary
7205            4        0       26          20.0  12500000.0
66488           0        1       26           3.0  12750000.0
12903           0        0       17           1.0  14411628.0
5305            4        3       26           5.0  15000000.0
9608            0        0       26          21.0  17500000.0
12700           0        2       10           5.0  19200000.0
28791           0        0       10           9.0  20000000.0
40586           0        1       26          13.0  21822250.0
65399           0        2       17           3.0  30468516.0
66910           3        1        3          21.0  45241312.0